export const COLOMBIA: Record<string, string[]> = {
  "Amazonas":          ["Leticia", "Puerto Nariño"],
  "Antioquia":         ["Medellín", "Bello", "Itagüí", "Envigado", "Apartadó", "Turbo", "Rionegro", "Sabaneta", "Caucasia"],
  "Arauca":            ["Arauca", "Saravena", "Tame"],
  "Atlántico":         ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia", "Sabanalarga"],
  "Bogotá D.C.":       ["Bogotá"],
  "Bolívar":           ["Cartagena", "Magangué", "El Carmen de Bolívar", "Mompox"],
  "Boyacá":            ["Tunja", "Duitama", "Sogamoso", "Paipa", "Villa de Leyva"],
  "Caldas":            ["Manizales", "Villamaría", "La Dorada", "Chinchiná"],
  "Caquetá":           ["Florencia", "San Vicente del Caguán"],
  "Casanare":          ["Yopal", "Aguazul", "Villanueva"],
  "Cauca":             ["Popayán", "Santander de Quilichao", "Puerto Tejada"],
  "Cesar":             ["Valledupar", "Aguachica", "Codazzi"],
  "Chocó":             ["Quibdó", "Bahía Solano", "Nuquí"],
  "Córdoba":           ["Montería", "Lorica", "Cereté", "Sahagún"],
  "Cundinamarca":      ["Soacha", "Facatativá", "Zipaquirá", "Chía", "Mosquera", "Madrid", "Fusagasugá", "Girardot"],
  "Guainía":           ["Inírida"],
  "Guaviare":          ["San José del Guaviare"],
  "Huila":             ["Neiva", "Pitalito", "Garzón", "La Plata"],
  "La Guajira":        ["Riohacha", "Maicao", "Uribia", "Manaure"],
  "Magdalena":         ["Santa Marta", "Ciénaga", "Fundación", "El Banco"],
  "Meta":              ["Villavicencio", "Acacías", "Granada", "Puerto López"],
  "Nariño":            ["Pasto", "Tumaco", "Ipiales", "Túquerres"],
  "Norte de Santander":["Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario"],
  "Putumayo":          ["Mocoa", "Puerto Asís", "La Hormiga"],
  "Quindío":           ["Armenia", "Calarcá", "Montenegro", "Quimbaya"],
  "Risaralda":         ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"],
  "San Andrés":        ["San Andrés", "Providencia"],
  "Santander":         ["Bucaramanga", "Floridablanca", "Girón", "Barrancabermeja", "Piedecuesta"],
  "Sucre":             ["Sincelejo", "Corozal", "Tolú", "Coveñas", "San Marcos"],
  "Tolima":            ["Ibagué", "Espinal", "Melgar", "Honda", "Girardot"],
  "Valle del Cauca":   ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago", "Jamundí"],
  "Vaupés":            ["Mitú"],
  "Vichada":           ["Puerto Carreño"],
};

export const DEPARTMENTS = Object.keys(COLOMBIA).sort();
