export type Difficulty = "Principiante" | "Intermedio" | "Avanzado" | "Todos los niveles";

export interface Spot {
  name: string;
  slug: string;
  region: string;
  regionSlug: string;
  disciplines: string[];
  windSeason: string;
  windStrength: string;
  difficulty: Difficulty;
  description: string;
  highlights: string[];
  tips: string[];
  coords: [number, number]; // [lat, lng]
  coverImage?: string;
}

export interface Region {
  name: string;
  slug: string;
  description: string;
  spots: Spot[];
}

export const REGIONS: Region[] = [
  {
    name: "La Guajira",
    slug: "la-guajira",
    description: "El paraíso del kitesurf en Colombia. Vientos alisios constantes de diciembre a agosto hacen de La Guajira el destino más codiciado del país.",
    spots: [
      {
        name: "Cabo de la Vela",
        slug: "cabo-de-la-vela",
        region: "La Guajira",
        regionSlug: "la-guajira",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Ago",
        windStrength: "15 – 30 nudos",
        difficulty: "Intermedio",
        description: "Cabo de la Vela es el spot más icónico de Colombia. Sus aguas planas dentro de la bahía y el viento alisio constante lo convierten en un destino de clase mundial. El entorno desértico, con dunas que caen directo al mar y el silencio absoluto de la Guajira, hacen que cada sesión sea una experiencia única.",
        highlights: [
          "Viento constante y predecible de diciembre a agosto",
          "Aguas planas en la bahía, ideales para freestyle y aprendizaje",
          "Entorno desértico único — dunas, cactos y mar",
          "Comunidad Wayuu activa, cultura local auténtica",
          "Varios kite schools y hospedajes sencillos",
        ],
        tips: [
          "Lleva efectivo — no hay cajeros en el cabo",
          "El viento es más fuerte en la tarde (12pm – 6pm)",
          "Reserva hospedaje con anticipación en temporada alta (Ene – Mar)",
          "Respeta las tradiciones de la comunidad Wayuu",
        ],
        coords: [12.2009, -72.1791],
      },
      {
        name: "Punta Gallinas",
        slug: "punta-gallinas",
        region: "La Guajira",
        regionSlug: "la-guajira",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – Jul",
        windStrength: "15 – 25 nudos",
        difficulty: "Avanzado",
        description: "El punto más septentrional de Sudamérica. Punta Gallinas es un destino remoto para kiters experimentados que buscan una aventura real. Las playas vírgenes, las dunas del desierto cayendo al Caribe y el viento constante crean un escenario épico e inalcanzable para la mayoría.",
        highlights: [
          "Punto más al norte de Sudamérica — experiencia única",
          "Playas completamente vírgenes sin turismo masivo",
          "Viento fuerte y constante durante todo el período",
          "Paisaje de dunas cayendo directamente al mar",
        ],
        tips: [
          "Acceso solo por carretera desde Uribia — viaje de varias horas",
          "Infraestructura mínima: lleva todo lo que necesitas",
          "Recomendado solo para kiters con experiencia sólida",
          "Tours organizados desde Riohacha o Cabo de la Vela",
        ],
        coords: [12.4624, -71.6701],
      },
      {
        name: "Riohacha",
        slug: "riohacha",
        region: "La Guajira",
        regionSlug: "la-guajira",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Abr",
        windStrength: "12 – 22 nudos",
        difficulty: "Todos los niveles",
        description: "La capital de La Guajira ofrece un spot accesible con infraestructura de ciudad. El malecón de Riohacha y sus alrededores tienen escuelas establecidas, hospedajes de todos los precios y acceso fácil desde el aeropuerto. Ideal como base para explorar otros spots de la región.",
        highlights: [
          "Ciudad con infraestructura completa — restaurantes, hospedajes, cajeros",
          "Aeropuerto local con vuelos desde Bogotá y otras ciudades",
          "Spot accesible y relativamente seguro para principiantes",
          "Base ideal para visitar Cabo de la Vela y Manaure",
        ],
        tips: [
          "El spot es más calmado que Cabo de la Vela — ideal para aprender",
          "Temporada alta: Enero a Marzo",
          "Cuidado con la corriente en días de viento fuerte",
        ],
        coords: [11.5449, -72.9072],
      },
      {
        name: "Mayapo",
        slug: "mayapo",
        region: "La Guajira",
        regionSlug: "la-guajira",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – May",
        windStrength: "12 – 20 nudos",
        difficulty: "Principiante",
        description: "A solo 30 minutos de Riohacha, Mayapo es una pequeña bahía de aguas protegidas perfecta para aprender kitesurf. El viento entra limpio desde el mar y las aguas planas dentro de la bahía permiten sesiones sin oleaje. Varios centros de kitesurf locales ofrecen clases aquí.",
        highlights: [
          "Aguas planas y protegidas — ideal para principiantes",
          "Viento limpio y constante durante la temporada",
          "Cercanía a Riohacha (30 min) — fácil acceso",
          "Escuelas de kitesurf establecidas",
        ],
        tips: [
          "Mejor en las mañanas — el viento es más suave y predecible",
          "Perfecta para primeras sesiones de kitesurf",
          "Los fines de semana puede estar concurrida",
        ],
        coords: [11.7000, -72.7833],
      },
      {
        name: "Manaure",
        slug: "manaure",
        region: "La Guajira",
        regionSlug: "la-guajira",
        disciplines: ["Kitesurf", "Windsurf"],
        windSeason: "Dic – Jun",
        windStrength: "15 – 28 nudos",
        difficulty: "Intermedio",
        description: "Conocida por sus salinas (las más grandes de Colombia), Manaure también esconde un excelente spot de kitesurf con viento fuerte y constante. Las aguas poco profundas de la costa y el paisaje industrial de las salinas crean un ambiente completamente distinto al del resto de la Guajira.",
        highlights: [
          "Viento fuerte y muy constante — similar a Cabo de la Vela",
          "Aguas planas y poco profundas",
          "Paisaje único de salinas — fotogénico",
          "Menos turistas que Cabo de la Vela",
        ],
        tips: [
          "El viento puede ser muy fuerte — equipo adecuado",
          "Combina la visita con un recorrido por las salinas",
          "Infraestructura básica — hospedaje sencillo disponible",
        ],
        coords: [11.7736, -72.4622],
      },
    ],
  },
  {
    name: "Cartagena y alrededores",
    slug: "cartagena",
    description: "La ciudad amurallada tiene sus propios spots de kitesurf. La Boquilla y sus lagunas son perfectas para principiantes, mientras que las islas cercanas ofrecen experiencias más aventureras.",
    spots: [
      {
        name: "La Boquilla",
        slug: "la-boquilla",
        region: "Cartagena",
        regionSlug: "cartagena",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – Mar",
        windStrength: "10 – 18 nudos",
        difficulty: "Principiante",
        description: "La Boquilla es el spot más popular de la región Caribe para aprender kitesurf. La laguna detrás del barrio ofrece aguas completamente planas y viento suave, protegida del oleaje del mar abierto. Varias escuelas de kitesurf operan aquí durante la temporada, con instructores certificados.",
        highlights: [
          "Laguna de aguas planas — ideal para primeras clases",
          "Escuelas certificadas de kitesurf",
          "A 20 minutos del centro histórico de Cartagena",
          "Acceso fácil y seguro",
        ],
        tips: [
          "El viento llega en las tardes (12pm – 5pm)",
          "La laguna puede estar llena los fines de semana",
          "Prueba el pescado frito en los restaurantes del barrio",
        ],
        coords: [10.4722, -75.5361],
      },
      {
        name: "Isla Tierra Bomba",
        slug: "isla-tierra-bomba",
        region: "Cartagena",
        regionSlug: "cartagena",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Mar",
        windStrength: "12 – 20 nudos",
        difficulty: "Intermedio",
        description: "La isla más cercana a Cartagena ofrece playas vírgenes y viento constante sin las multitudes del centro. El acceso es solo en lancha desde el muelle turístico, lo que le da un toque de aventura. Las aguas cristalinas y el viento del Caribe hacen de Tierra Bomba una joya poco conocida.",
        highlights: [
          "Playa tranquila sin turismo masivo",
          "Aguas cristalinas del Caribe",
          "Viento constante en temporada",
          "Fácil de combinar con paseo en lancha",
        ],
        tips: [
          "Lancha desde el muelle de La Bodeguita — 15-20 min",
          "Lleva todo lo que necesites — pocos servicios en la isla",
          "Mejor de lunes a viernes para evitar turistas",
        ],
        coords: [10.3700, -75.5700],
      },
      {
        name: "Barú – Playa Blanca",
        slug: "baru-playa-blanca",
        region: "Cartagena",
        regionSlug: "cartagena",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – Mar",
        windStrength: "10 – 18 nudos",
        difficulty: "Intermedio",
        description: "Playa Blanca en la isla de Barú combina uno de los paisajes más hermosos del Caribe colombiano con condiciones aceptables para el kitesurf. La playa de arena blanca y aguas turquesas es ya un destino turístico de primer nivel, pero los kiters pueden disfrutar del extremo sur de la playa con menos aglomeración.",
        highlights: [
          "Una de las playas más bonitas de Colombia",
          "Aguas turquesas y arena blanca",
          "Varios hostales y campamentos en la playa",
          "Excelente para combinar kitesesh con días de playa",
        ],
        tips: [
          "Acceso en lancha desde Cartagena (1.5h) o por carretera",
          "Kitesurf en el extremo sur de la playa (menos turistas)",
          "Muy concurrida en temporada alta (Dic–Ene)",
        ],
        coords: [10.2067, -75.6447],
      },
    ],
  },
  {
    name: "Atlántico",
    slug: "atlantico",
    description: "El departamento del Atlántico esconde varios spots poco conocidos al norte de Barranquilla. Salinas del Rey y Puerto Velero son los favoritos de los kiters locales.",
    spots: [
      {
        name: "Salinas del Rey",
        slug: "salinas-del-rey",
        region: "Atlántico",
        regionSlug: "atlantico",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Abr",
        windStrength: "15 – 25 nudos",
        difficulty: "Intermedio",
        description: "Salinas del Rey es el spot más técnico del Atlántico. Su configuración de laguna salina rodeada de playas ofrece condiciones únicas: viento fuerte encanalado por la geografía y aguas planas para freestyle. Es el favorito de los kiters avanzados de Barranquilla.",
        highlights: [
          "Viento fuerte y encanalado — condiciones técnicas únicas",
          "Laguna salina con aguas planas",
          "Comunidad de kiters barranquilleros activa",
          "A 1.5h de Barranquilla",
        ],
        tips: [
          "Viento más fuerte en enero y febrero",
          "Llevar equipo propio — servicios limitados",
          "Ideal para freestyle y big air con viento fuerte",
        ],
        coords: [10.9833, -74.9667],
      },
      {
        name: "Santa Verónica",
        slug: "santa-veronica",
        region: "Atlántico",
        regionSlug: "atlantico",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – Mar",
        windStrength: "12 – 20 nudos",
        difficulty: "Todos los niveles",
        description: "Playa de fácil acceso desde Barranquilla, Santa Verónica es el punto de encuentro de los kiters de la región. Con servicios básicos y una playa larga, ofrece espacio suficiente para sesiones cómodas. El viento llega del noreste y las aguas son moderadamente planas.",
        highlights: [
          "Acceso directo desde Barranquilla (1h)",
          "Playa larga con buen espacio",
          "Comunidad local activa",
          "Servicios básicos disponibles",
        ],
        tips: [
          "El viento llega mejor en las tardes",
          "Fin de semana puede estar llena de turistas — llega temprano",
        ],
        coords: [11.0500, -74.9000],
      },
      {
        name: "Puerto Velero",
        slug: "puerto-velero",
        region: "Atlántico",
        regionSlug: "atlantico",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Abr",
        windStrength: "12 – 22 nudos",
        difficulty: "Todos los niveles",
        description: "Puerto Velero es una pequeña bahía protegida al norte de Barranquilla con condiciones consistentes durante la temporada de alisios. La bahía natural crea aguas más planas que el mar abierto, lo que la hace adecuada para todos los niveles. Tiene hospedajes y restaurantes establecidos.",
        highlights: [
          "Bahía protegida — aguas más planas",
          "Hospedajes y restaurantes en el pueblo",
          "Bueno para todos los niveles",
          "Acceso fácil desde Barranquilla",
        ],
        tips: [
          "Temporada alta: Enero a Marzo",
          "Los fines de semana hay mucho tráfico de lanchas — cuidado",
        ],
        coords: [10.9167, -74.9500],
      },
    ],
  },
  {
    name: "Santa Marta y Magdalena",
    slug: "santa-marta",
    description: "La ciudad más antigua de Colombia tiene una costa con viento constante entre diciembre y marzo. Pozos Colorados y El Rodadero son los spots más conocidos de la zona.",
    spots: [
      {
        name: "El Rodadero",
        slug: "el-rodadero",
        region: "Santa Marta",
        regionSlug: "santa-marta",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – Mar",
        windStrength: "12 – 20 nudos",
        difficulty: "Intermedio",
        description: "El balneario más popular de Santa Marta también tiene su spot de kitesurf. Aunque la zona turística puede estar concurrida, el extremo norte de la playa ofrece espacio para los kiters. El viento del noreste llega limpio en temporada y las aguas son relativamente planas.",
        highlights: [
          "Fácil acceso desde Santa Marta (10 min)",
          "Infraestructura completa de ciudad turística",
          "Buen viento en temporada de alisios",
        ],
        tips: [
          "Kitesurf en el extremo norte de la playa (lejos de los turistas)",
          "Muy concurrido en temporada de vacaciones colombianas",
          "El viento llega mejor en las tardes",
        ],
        coords: [11.2167, -74.2333],
      },
      {
        name: "Pozos Colorados",
        slug: "pozos-colorados",
        region: "Santa Marta",
        regionSlug: "santa-marta",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Mar",
        windStrength: "15 – 25 nudos",
        difficulty: "Intermedio",
        description: "El mejor spot de Santa Marta para kitesurf. Pozos Colorados, ubicado entre Santa Marta y la zona del Aeropuerto, tiene viento fuerte y constante con aguas moderadamente planas. Es el punto de encuentro de los kiters samarios y tiene una pequeña comunidad organizada.",
        highlights: [
          "Mejor viento de la zona de Santa Marta",
          "Comunidad de kiters local establecida",
          "Playa con espacio suficiente",
          "Cerca del aeropuerto de Santa Marta",
        ],
        tips: [
          "El viento es más fuerte que en El Rodadero",
          "Ideal para kiters con experiencia previa",
          "Temporada alta: Enero a Marzo",
        ],
        coords: [11.2500, -74.2167],
      },
      {
        name: "Taganga",
        slug: "taganga",
        region: "Santa Marta",
        regionSlug: "santa-marta",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – Feb",
        windStrength: "10 – 18 nudos",
        difficulty: "Principiante",
        description: "El pequeño pueblo de pescadores a 10 minutos de Santa Marta tiene una bahía perfecta para sesiones tranquilas. El viento es más suave que en otros spots de la zona, lo que la hace ideal para principiantes. La mezcla de mochileros, pescadores y deportistas le da un ambiente muy especial.",
        highlights: [
          "Bahía tranquila con aguas planas",
          "Viento suave — ideal para principiantes",
          "Ambiente de pueblo pesquero auténtico",
          "A 10 min de Santa Marta",
        ],
        tips: [
          "Viento más suave — llevar cometa más grande",
          "La bahía es pequeña — cuidado con las embarcaciones de pesca",
          "Buenas opciones de hospedaje económico",
        ],
        coords: [11.2681, -74.1900],
      },
      {
        name: "Palomino",
        slug: "palomino",
        region: "Santa Marta / La Guajira",
        regionSlug: "santa-marta",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Mar",
        windStrength: "12 – 22 nudos",
        difficulty: "Intermedio",
        description: "Palomino es quizás la playa más bella del Caribe colombiano. Rodeada de selva tropical y sierra nevada, su playa larga y solitaria tiene viento constante en temporada. Aunque el oleaje puede ser fuerte (waves), los kiters de nivel intermedio y avanzado tienen mucho espacio para sesiones épicas.",
        highlights: [
          "Una de las playas más bonitas de Colombia",
          "Playa larga y solitaria con selva al fondo",
          "Buen viento en temporada",
          "Ambiente tranquilo y alternativo",
        ],
        tips: [
          "Puede haber oleaje — no recomendada para principiantes",
          "Hospedaje en eco-hostales y fincas",
          "La desembocadura del río Palomino es un spot adicional",
        ],
        coords: [11.2508, -73.5847],
      },
    ],
  },
  {
    name: "Lagos e Interiores",
    slug: "lagos",
    description: "Colombia tiene algunos de los mejores spots de kitesurf en agua dulce del mundo. Lago Calima es el favorito con viento térmico predecible casi todo el año.",
    spots: [
      {
        name: "Lago Calima",
        slug: "lago-calima",
        region: "Valle del Cauca",
        regionSlug: "lagos",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf", "Wakeboard", "Paddle"],
        windSeason: "Todo el año",
        windStrength: "15 – 35 nudos",
        difficulty: "Todos los niveles",
        description: "Lago Calima es sin duda el spot más popular de Colombia y uno de los mejores spots de agua dulce del mundo. El viento térmico que llega cada tarde (entre 12pm y 6pm) es tan predecible como un reloj — en más de 300 días al año. Sus aguas planas y frías, rodeadas de montañas verdes, crean un ambiente único a 1.500 metros de altitud. Daríen, el pueblo a orillas del lago, tiene varios kite schools, hostales y restaurantes especializados.",
        highlights: [
          "Más de 300 días de viento al año — el más consistente de Colombia",
          "Viento térmico predecible: llega entre 12pm y 6pm",
          "Aguas planas y frías — perfectas para aprendizaje y freestyle",
          "Kite schools establecidas con instructores certificados",
          "A solo 2h de Cali y 5h de Bogotá",
          "Ambiente de comunidad kiter muy activo",
        ],
        tips: [
          "El viento llega alrededor de las 12pm — no madrugues",
          "Agua fría (15-18°C) — lleva traje de neopreno",
          "Altitud 1.500m — el equipo vuela diferente, ajusta tu cometa",
          "Reserva con anticipación en temporada alta (Jul–Ago y Dic)",
          "Daríen tiene todo lo que necesitas para una semana",
        ],
        coords: [3.9167, -76.4667],
      },
      {
        name: "Embalse de Tominé",
        slug: "embalse-de-tomine",
        region: "Cundinamarca",
        regionSlug: "lagos",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Todo el año",
        windStrength: "10 – 20 nudos",
        difficulty: "Intermedio",
        description: "A solo 45 minutos de Bogotá, el Embalse de Tominé ofrece sesiones de kitesurf a 2.600 metros de altitud. El viento termal de la tarde llega con regularidad especialmente en verano. Las vistas de las montañas y el pueblo colonial de Guatavita hacen del entorno algo especial. Es el spot de los kiters bogotanos.",
        highlights: [
          "A 45 minutos de Bogotá — fácil escapada de fin de semana",
          "Sesiones a 2.600 m de altitud",
          "Viento termal de tarde en temporada seca",
          "Combo con visita al pueblo de Guatavita",
        ],
        tips: [
          "Altitud alta — el cuerpo gasta más energía, hidrátate bien",
          "El viento es más irregular que en Calima",
          "Mucho frío — neopreno completo recomendado",
          "Mejor en temporada seca (Jun–Ago y Dic–Feb)",
        ],
        coords: [4.9833, -73.7833],
      },
      {
        name: "Guatapé",
        slug: "guatape",
        region: "Antioquia",
        regionSlug: "lagos",
        disciplines: ["Kitesurf", "Wingfoil", "Wakeboard", "Paddle"],
        windSeason: "Jun – Ago",
        windStrength: "8 – 18 nudos",
        difficulty: "Intermedio",
        description: "El embalse de Guatapé, famoso por la Piedra del Peñón, tiene también condiciones para kitesurf y windfoil. El viento es más variable que en Calima, pero la belleza del entorno — con cientos de islotes cubiertos de selva — compensa con creces. Una visita combinada con La Piedra del Peñón es perfecta.",
        highlights: [
          "Paisaje espectacular de islotes y selva",
          "La Piedra del Peñón a pocos kilómetros",
          "Aguas tranquilas y cálidas",
          "Ideal para combinar con turismo en el pueblo",
        ],
        tips: [
          "El viento es variable — no garantizado todo el año",
          "Mejor en temporada seca de mitad de año (Jun–Ago)",
          "El pueblo tiene buena oferta gastronómica y de hospedaje",
        ],
        coords: [6.2333, -75.1500],
      },
      {
        name: "Represa de Prado",
        slug: "represa-de-prado",
        region: "Tolima",
        regionSlug: "lagos",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf", "Wakeboard"],
        windSeason: "Jun – Sep",
        windStrength: "10 – 20 nudos",
        difficulty: "Todos los niveles",
        description: "La Represa de Prado es el embalse más grande de Colombia y uno de los spots de aguas interiores menos conocidos del país. Con agua cálida (27°C), viento termal en temporada y playas de arena, es una alternativa tropical a Lago Calima para los kiters del interior del país.",
        highlights: [
          "Agua cálida (27°C) — sin neopreno",
          "Embalse enorme con mucho espacio",
          "Playas de arena dentro del embalse",
          "Poco conocido — pocos kiters, mucho espacio",
        ],
        tips: [
          "El viento es más variable que en Calima",
          "Acceso desde Bogotá: 4h por la ruta del Tolima",
          "Temporada seca (Jun–Sep) para mejor viento",
        ],
        coords: [3.7167, -74.9167],
      },
    ],
  },
  {
    name: "Otros Spots",
    slug: "otros",
    description: "Más spots a lo largo del Caribe colombiano y las islas del archipiélago. San Andrés y Providencia ofrecen aguas turquesas del Caribe en un entorno de isla.",
    spots: [
      {
        name: "Coveñas",
        slug: "covenas",
        region: "Sucre",
        regionSlug: "otros",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Mar",
        windStrength: "12 – 22 nudos",
        difficulty: "Todos los niveles",
        description: "Coveñas es uno de los balnearios más populares del Caribe colombiano y tiene buenas condiciones para el kitesurf en temporada de alisios. La playa larga y las aguas cálidas del Golfo de Morrosquillo ofrecen un entorno relajado con infraestructura de turismo establecida.",
        highlights: [
          "Playa larga con espacio suficiente",
          "Aguas cálidas y tranquilas del Golfo",
          "Buena infraestructura turística",
          "Fácil acceso desde Cartagena (3h)",
        ],
        tips: [
          "Temporada alta: Diciembre a Marzo",
          "El Golfo de Morrosquillo es más tranquilo que el Caribe abierto",
          "Combine con visita a las islas del Rosario",
        ],
        coords: [9.4167, -75.6833],
      },
      {
        name: "Tolú",
        slug: "tolu",
        region: "Sucre",
        regionSlug: "otros",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – Mar",
        windStrength: "10 – 18 nudos",
        difficulty: "Principiante",
        description: "A pocos kilómetros de Coveñas, Tolú tiene un spot con condiciones más suaves y aguas muy planas del Golfo. Ideal para principiantes que buscan sus primeras sesiones en el mar. El pueblo tiene una buena oferta gastronómica y de hospedaje.",
        highlights: [
          "Aguas muy planas del Golfo — ideal para aprender",
          "Viento suave y manejable",
          "Pueblo con buena gastronomía de mariscos",
        ],
        tips: [
          "Mejor para principiantes que Coveñas",
          "Combinar con visita a las Islas de San Bernardo",
        ],
        coords: [9.5167, -75.5833],
      },
      {
        name: "San Andrés",
        slug: "san-andres",
        region: "Archipiélago de San Andrés",
        regionSlug: "otros",
        disciplines: ["Kitesurf", "Wingfoil", "Windsurf"],
        windSeason: "Dic – Mar",
        windStrength: "15 – 25 nudos",
        difficulty: "Intermedio",
        description: "La isla de San Andrés tiene aguas turquesas del Caribe profundo con viento constante en temporada. La zona norte (El Cove) y San Luis son los spots más conocidos para kitesurf. Las aguas cristalinas y el ambiente caribeño hacen de cada sesión algo especial, aunque la logística de llevar equipo a la isla puede ser complicada.",
        highlights: [
          "Aguas turquesas del Caribe profundo",
          "Viento consistente en temporada de alisios",
          "La 'Sea of Seven Colors' — paisaje único",
          "Vuelos directos desde Bogotá, Medellín y Cali",
        ],
        tips: [
          "Llevar equipo propio — alquiler limitado en la isla",
          "Zona norte (El Cove) y San Luis son los mejores spots",
          "Temporada alta: Diciembre a Marzo",
          "Combinar con snorkel y diving — arrecife de coral",
        ],
        coords: [12.5847, -81.7006],
      },
      {
        name: "Providencia",
        slug: "providencia",
        region: "Archipiélago de San Andrés",
        regionSlug: "otros",
        disciplines: ["Kitesurf", "Wingfoil"],
        windSeason: "Dic – Mar",
        windStrength: "12 – 22 nudos",
        difficulty: "Avanzado",
        description: "Providencia es una de las islas más remotas y vírgenes de Colombia. Con el segundo arrecife de barrera más grande del mundo y aguas de color imposible, ofrece una experiencia de kitesurf única para quienes están dispuestos a hacer el viaje. Infraestructura mínima pero belleza máxima.",
        highlights: [
          "Segundo arrecife de barrera más grande del mundo",
          "Aguas turquesas y prístinas",
          "Isla remota con turismo muy bajo",
          "Naturaleza completamente virgen",
        ],
        tips: [
          "Acceso solo desde San Andrés — vuelo pequeño o lancha (8h)",
          "Llevar TODO el equipo — no hay alquiler",
          "Solo para kiters con experiencia — pocas opciones de rescate",
          "Reserva con mucha anticipación — hospedaje muy limitado",
        ],
        coords: [13.3500, -81.3700],
      },
    ],
  },
];

export function getSpotBySlug(slug: string): Spot | undefined {
  for (const region of REGIONS) {
    const spot = region.spots.find(s => s.slug === slug);
    if (spot) return spot;
  }
  return undefined;
}

export function getAllSpotsFlat(): Spot[] {
  return REGIONS.flatMap(r => r.spots);
}
